PUT http://localhost:3003/api/blogs/66ebd09a9bee08ac3c161b79 HTTP/1.1
Content-Type: application/json

{
  "title": "Prodigy Programmers",
  "author": "TheTanweer",
  "url": "http://localhost:3003",
  "likes": 11981
}
