POST http://localhost:3001/api/notes
Content-Type: application/json

{
  "content": "Existing code & tests need to be changed when user is added to the system",
  "important": true,
  "userId": "66fecda12397e47bf9b49b7a"
}
